# AI HACK 2018 GWAS (PCA on genome matrix)

In [1]:
import numpy as np
import scipy as sp
import pandas as pd

## 1. Load de filez

Load the SNP files for chromosomes 15, 16, 17. 

In [2]:
SNP15 = pd.read_csv('D:/AI_Hack/GWAS_files/AIHack-SNP-Matrix-15.csv')

In [3]:
SNP16 = pd.read_csv('D:/AI_Hack/GWAS_files/AIHack-SNP-Matrix-16.csv')

In [4]:
SNP17 = pd.read_csv('D:/AI_Hack/GWAS_files/AIHack-SNP-Matrix-17.csv')

Load the patient data file and the computed SNP PCs.

In [5]:
SNP_patients = pd.read_csv('D:/AI_Hack/GWAS_files/AIHack-Clinical.csv')
SNP_PCs = pd.read_csv('D:/AI_Hack/GWAS_files/AIHack-PCs.csv')

In [6]:
SNP_patients.head()

Unnamed: 0  FamID  CAD  sex  age     tg   hdl    ldl
0       10002  10002    1    1   60    NaN   NaN    NaN
1       10004  10004    1    2   50   55.0  23.0   75.0
2       10005  10005    1    1   55  105.0  37.0   69.0
3       10007  10007    1    1   52  314.0  54.0  108.0
4       10008  10008    1    1   58  161.0  40.0   94.0

- Low-density lipoprotein (LDL): There are 2 types of lipoproteins that cholesterols in your blood flows on. LDL makes up most of the body’s cholesterols, and high levels raises your risk of heart disease and stroke.
- High-density lipoprotein (HDL): HDL absorbs cholesterols and carries it back to the liver. High levels can have the converse effects of LDL.
- Triglycerides (TG): Triglycerides are a type of lipid found in the human blood. They are usually stored in the fat cells. Triglycerides store unused calories and provide the human body with energy, whereas cholesterols are used to build cells and some hormones. Often high Triglycerides are associated with other conditions that increase the risk of heart disease.
- Coronary artery disease (CAD): This is a condition in which the major blood vessels in the body, such as the coronary arteries, become damaged. This can lead to heart attacks or strokes.
- Angiography (angiography): Coronary angiography is a method used to use the X-ray to see the heart’s vessels inside a person’s body.

In [7]:
SNP17.head()

Unnamed: 0  rs11025370  rs8066551  rs4890198  rs7220744  rs11654845  \
0       10002           3          2          3          3           2   
1       10004           2          3          2          3           3   
2       10005           3          3          3          3           3   
3       10007           2          1          2          3           3   
4       10008           3          2          2          3           3   

   rs1129996  rs9907749  rs9913674  rs759974    ...      rs7224733  \
0          3          3          2         3    ...              1   
1          3          3          2         3    ...              2   
2          3          3          2         2    ...              3   
3          3          3          3         1    ...              1   
4          3          3          3         2    ...              2   

   rs10852789  rs1143006  rs7406119  rs6502040  rs9911217  rs7406561  \
0           3          3          1          3          3          2   
1           3          3          2          3          3          2   
2           2          2          3          3          1          3   
3           3          3          1          3          3          2   
4           3          3          2          3          2          0   

   rs8077967  rs7502145  rs4986109  
0          2          2          2  
1          2          3          2  
2          3          2          1  
3          3          3          2  
4          0          3          3  

[5 rows x 19940 columns]

In [79]:
SNP15.head()

rs12905389  rs6599751  rs9744388  rs9744157  rs7171651  rs10152550  \
0           2          0          2          3          3           2   
1           2          3          2          3          3           2   
2           3          3          3          3          3           3   
3           2          0          2          3          3           3   
4           2          0          2          3          2           2   

   rs12916870  rs7179358  rs4932079  rs6599857    ...      rs7182334  \
0           2          3          2          3    ...              2   
1           2          2          3          3    ...              3   
2           3          1          3          3    ...              3   
3           3          2          2          3    ...              2   
4           2          2          2          3    ...              2   

   rs1399026  rs976273  rs11639153  rs7165135  rs7169385  rs1355871  \
0          3         3           2          2          3          2   
1          1         1           3          3          3          3   
2          2         1           3          3          3          3   
3          2         2           3          2          3          3   
4          2         1           3          2          3          3   

   rs11637017  rs8029360  rs1533309  
0           2          3          1  
1           3          2          2  
2           3          2          2  
3           3          1          3  
4           3          2          2  

[5 rows x 25900 columns]

### Cleaning up the data...missing values etc. 

In [92]:
import collections

In [97]:
num_snp = len(SNP15.values[0])

In [98]:
#num_snp = 16383
dist = np.array([0.25,0.5,0.25])

In [99]:
data = []
data1 = []
for i in range(num_snp):
    col = SNP15.iloc[:,i]
    col = np.array(col)
    dist = []
   
    zero = 0 
    one = 0 
    two = 0
    three = 0
   
    for j in col:
        if j == 0:
            zero += 1 
        if j == 1 :
            one += 1
        if j == 2:
            two += 1
        if j == 3: 
            three += 1
           
    dist = np.array([zero, one,two,three],dtype=float)
    prob = dist/1401
   
    a = np.sqrt(prob[1])
    b = np.sqrt(prob[3])
    c = a + b 
   
    data.append(c)
    data1.append(prob)

In [102]:
d = 0
bad_indices = []
true_data = []
true_data1 = []
for i in range(len(data1)):
    if data1[i][0] < 0.05:
        true_data.append(data1[i])
        true_data1.append(data[i])
for i in range(len(true_data)):
    if true_data1[i] < 1.025 and true_data1[i] > 0.975:
        d += 1
        #print(d)
        #print(data1[i])
    else:
        bad_indices.append(i)

#df = pd.DataFrame(np.matrix(true_data))
#df.to_csv("data.csv")

In [115]:
true_data

[array([0.00713776, 0.06138473, 0.39400428, 0.53747323]),
 array([0.03640257, 0.03640257, 0.29122056, 0.6359743 ]),
 array([7.13775874e-04, 2.85510350e-03, 1.04925054e-01, 8.91506067e-01]),
 array([0.01498929, 0.07209136, 0.4111349 , 0.50178444]),
 array([0.03640257, 0.14703783, 0.50107066, 0.31548894]),
 array([0.0028551 , 0.13276231, 0.48179872, 0.38258387]),
 array([0.        , 0.06281228, 0.38900785, 0.54817987]),
 array([0.00856531, 0.        , 0.        , 0.99143469]),
 array([0.02855103, 0.01855817, 0.21698787, 0.73590293]),
 array([0.04496788, 0.01142041, 0.21984297, 0.72376874]),
 array([0.00142755, 0.        , 0.00214133, 0.99643112]),
 array([0.04354033, 0.0592434 , 0.31263383, 0.58458244]),
 array([0.02426838, 0.0385439 , 0.27408994, 0.66309779]),
 array([3.42612420e-02, 7.13775874e-04, 3.42612420e-02, 9.30763740e-01]),
 array([0.00642398, 0.        , 0.00428266, 0.98929336]),
 array([0.02712348, 0.00356888, 0.11277659, 0.85653105]),
 array([0.03283369, 0.0856531 , 0.311206

## 2. Constructing the genetic relationship matrix $\psi$ (GRM)

To compute the PCA we need a data array in the form of a "correlation matrix". We can't simply use the given chromosome matrices due to the categorical nature of the SNP values (0- missing data 1- zero recessive alleles 2- one 3- two).  <br>
For each chromosome (15, 16, 17), we have a $M \times N$ genotype matrix $\mathbf{X}$, where $M$ is the number fo SNPs and $N$ is the number of individuals in the study. Each matrix entry $x_{ij}$ takes a value {0,1,2} which represents the count of variant alleles for an individual at SNP $i$. From here, we construct the $M \times N$  normalised genomic matrix $\mathbf{Y}$ where each row $\mathbf{y_{i}}$ has approximately mean 0 and variance 1 for SNPs in the Hardy-Weinberg equilibrium (Galinsky *et al*, 2016)(Price, *et al*, 2006). <br>

$\mu_i = \frac{\sum_{j=1}^{N}x_{ij}}{N_i}$ <br>

$p_i = \frac{1+\sum_{j=1}^{N}x_{ij}}{2+2N_i}$ <br>

$y_{ij} = \frac{x_{ij}-\mu_{i}}{\sqrt{p_{i}(1-p_{i})}}$ <br>


where $p_i$ is the sample allele frequency for SNP $i$.

** It seems like there's different definitions of this across different papers!!!** <br>

In [23]:
# Format the matrix into the format above 
X_15 = np.transpose(SNP15.values)
X_16 = np.transpose(SNP16.values)
X_17 = np.transpose(SNP17.values)

Drop the first (patients) columns from the 3 SNP dataframes. (somehow this was automatically done somehow?)

Inspect the SNP matrix for one chromosome.

In [21]:
# SNP15.drop("Unnamed: 0", axis=1)
# SNP16.drop("Unnamed: 0", axis=1)
# SNP17.drop("Unnamed: 0", axis=1)

"Fake" cleaning on data first for code testing...simply 3->2, 2->1, 1->0.

In [25]:
X_15 
dic = np.zeros_like(X_15)
k = 0
for i in X_15:
    dic[k] = [j-1 if j != 0 else j for j in i ]
    k+= 1

In [26]:
dic

array([[1, 1, 2, ..., 2, 2, 1],
       [0, 2, 2, ..., 2, 0, 2],
       [1, 1, 2, ..., 2, 2, 2],
       ...,
       [1, 2, 2, ..., 1, 2, 1],
       [2, 1, 1, ..., 1, 1, 2],
       [0, 1, 1, ..., 1, 1, 0]], dtype=int64)

In [28]:
print (X_15.shape)
print (X_16.shape)
print (X_17.shape)

(25900, 1401)
(27592, 1401)
(19940, 1401)


In [29]:
X_15[0,:].shape #Expect 1401 sample values for this SNP for chromosome 15 

(1401,)

Code the GRM matrix for an input genotype matrix X. 

In [164]:
len(X_15[0,:])

1401

In [121]:
def normY(X):
    '''
    Returns the normalised matrix Y of a genotype matrix X. 
    '''
    normY = np.zeros_like(X, dtype=float)
    for i in range(len(X)):
        mu_i = np.mean(X[i])
        p_i = (1.+np.sum(X[i]))/(2.+2.*len(X[i]))
        normY[i] = [np.float(j - mu_i)/np.sqrt(p_i*(1-p_i)) for j in X[i]]
            
    return normY 

In [122]:
normY_15 = normY(dic)

Then, the genomic relationship matrix (GRM) $\psi$ is given by:

$\mathbf{\psi} = \mathbf{Y}^{T}\mathbf{Y}/M$

## 3. Simple PCA

We employ principal component analysis (PCA) as a dimensionality reduction tool to infer obscure population structure from the SNP data. 

In [52]:
from sklearn.decomposition import PCA

In [59]:
#Test example 
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
# load dataset into Pandas DataFrame
df = pd.read_csv(url, names=['sepal length','sepal width','petal length','petal width','target'])

In [60]:
from sklearn.preprocessing import StandardScaler
features = ['sepal length', 'sepal width', 'petal length', 'petal width']
# Separating out the features
x = df.loc[:, features].values
# Separating out the target
y = df.loc[:,['target']].values
# Standardizing the features
x = StandardScaler().fit_transform(x)

In [61]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1', 'principal component 2'])

In [62]:
print(x.shape)
principalDf.head()

(150, 4)


principal component 1  principal component 2
0              -2.264542               0.505704
1              -2.086426              -0.655405
2              -2.367950              -0.318477
3              -2.304197              -0.575368
4              -2.388777               0.674767

## Apply the PCA to our SNP matrix 
The leading principal components of $\mathbf{Y}$ are obtained by performing the eigendecomposition of the GRM.

Perform first on chromosome 15

In [73]:
normY_15

array([[-1.06169295, -1.06169295,  1.20228243, ...,  1.20228243,
         1.20228243, -1.06169295],
       [-2.79446469,  1.43116405,  1.43116405, ...,  1.43116405,
        -2.79446469,  1.43116405],
       [-1.3625908 , -1.3625908 ,  1.05691453, ...,  1.05691453,
         1.05691453,  1.05691453],
       ...,
       [-0.56676853,  1.5118773 ,  1.5118773 , ..., -0.56676853,
         1.5118773 , -0.56676853],
       [ 1.98861196, -0.0114206 , -0.0114206 , ..., -0.0114206 ,
        -0.0114206 ,  1.98861196],
       [-1.93814243,  0.06284323,  0.06284323, ...,  0.06284323,
         0.06284323, -1.93814243]])

In [65]:
psi = np.matmul(np.transpose(normY_15), normY_15) 

In [78]:
psi.shape

(1401, 1401)

Normalised GRM $\mathbf{\psi}$

In [88]:
GRM_15 = psi/len(normY_15)  #GRM 
GRM_15

array([[ 2.60462151,  0.11445133,  0.08938734, ..., -0.0937587 ,
         0.06993932,  0.00786826],
       [ 0.11445133,  2.30070989,  0.06785683, ..., -0.01531052,
         0.03545821,  0.02567718],
       [ 0.08938734,  0.06785683,  2.03755026, ..., -0.00580748,
         0.05086665, -0.03541635],
       ...,
       [-0.0937587 , -0.01531052, -0.00580748, ...,  1.7620271 ,
         0.01292085, -0.04052587],
       [ 0.06993932,  0.03545821,  0.05086665, ...,  0.01292085,
         4.24782814,  0.06406262],
       [ 0.00786826,  0.02567718, -0.03541635, ..., -0.04052587,
         0.06406262,  2.25620814]])

In [89]:
pca0 = PCA(n_components=10)
principalComponents0 = pca0.fit_transform(GRM_15)

In [110]:
principalComponents0

array([[ 0.47402344,  0.00584342,  1.03424675, ..., -0.22891216,
         0.23798779,  0.3039218 ],
       [ 0.12467446, -0.89694626,  0.19525452, ..., -0.5007353 ,
         0.04813514,  0.14138865],
       [ 0.51783149, -0.20997004,  0.60141023, ...,  0.0636182 ,
         0.18103874,  0.06398722],
       ...,
       [-0.51843358,  0.03020687, -0.23759396, ...,  0.02037874,
        -0.1279346 , -0.14603622],
       [-0.37103532,  0.85697932,  0.89908645, ..., -0.38568377,
         0.29157161, -0.26820006],
       [-0.36957807,  0.43156855,  0.58383537, ..., -0.37120189,
         0.1026773 ,  0.01377289]])

Store to Pandas dataframe.

In [111]:
principalDf = pd.DataFrame(data = principalComponents0
             , columns = ['PC1', 'PC2','PC3','PC4','PC5','PC6','PC7','PC8','PC9','PC10'])
principalDf

PC1       PC2       PC3       PC4       PC5       PC6       PC7  \
0     0.474023  0.005843  1.034247 -0.770833  0.735158  0.066589  0.772393   
1     0.124674 -0.896946  0.195255  0.149607  0.905009  0.455568  0.202637   
2     0.517831 -0.209970  0.601410 -0.539244  0.019895  0.035760 -0.436585   
3     0.824487 -0.033219  0.733139 -0.313377  0.380806 -0.027331  0.445687   
4     0.031520 -0.807266  0.085693  0.380503  0.675800  0.542039 -0.234848   
5     0.012864 -0.218435 -0.419563  0.335189  1.001937  0.716424 -0.241797   
6    -0.175024 -0.155013  0.358903 -0.527486 -0.119304 -0.189587  0.208031   
7    -0.118110  0.184875  0.012854  0.106684  0.216353  0.478558  0.220347   
8     2.480173 -0.158334 -0.679098  0.176204 -0.434363 -0.184415 -0.113648   
9     3.265383  0.200077 -0.362085  0.707342  0.003045 -0.815502  0.291743   
10   -0.132111 -0.589101  0.335235  0.047719 -0.115398  0.162228  0.033023   
11    2.765892 -0.076996 -0.572236  0.102256 -0.282864 -0.243031  0.048883   
12    2.977025 -0.025350 -0.422347  0.379886 -0.081514 -0.391776  0.038046   
13    2.559669  0.862109 -0.584840  0.332320 -0.659934 -0.124287  0.160289   
14    4.003143  0.265817 -0.351404  0.525567 -0.189527 -0.779710  0.133713   
15   -0.154456 -0.116352  0.279554 -0.289583  0.393480 -0.168231  0.170830   
16    0.053422 -0.166541  0.764132  0.742920 -0.634077  0.522759  0.087638   
17   -0.216412 -0.322444  0.601591 -0.094019 -0.077706 -0.204745  0.210190   
18    0.662512 -0.297625  0.108922 -0.512399  0.139560  0.189179  0.595515   
19    0.188166  0.316590 -0.455333  0.201904 -0.096160 -0.332683 -0.056205   
20    2.736855 -0.216693 -0.627370  0.224513 -0.169648 -0.001949 -0.052591   
21   -0.452650 -0.087136 -0.205779  0.042456 -0.363377  0.188587 -0.052534   
22    0.111286 -0.626444  0.216914 -0.003984  0.446951  0.217689  0.320880   
23   -0.616031  0.349430 -0.244953 -0.296513  0.395311  0.263328  0.663834   
24   -0.680779  0.459508 -0.010088 -0.143153  0.395080 -0.351287  0.388239   
25   -0.137602 -0.242408  0.123782 -0.309310  0.301494  0.008450  0.553033   
26   -0.042385 -0.108535  0.352939 -0.888381  0.201557  0.141250 -0.051757   
27   -0.502105 -0.168353  0.512696 -0.208352 -0.248441 -0.213551 -0.137656   
28   -0.139878 -0.148401  0.262063 -0.762647  0.374537  0.076655  0.226129   
29   -0.543456  0.255690 -0.027172 -0.613863  0.183489  0.147625  0.569277   
...        ...       ...       ...       ...       ...       ...       ...   
1371 -0.588318  1.083236  0.461899 -0.125118  0.090292  0.091200 -0.015317   
1372 -0.176871 -0.042635  0.912521 -0.195280 -0.546396  0.220861  0.008780   
1373 -0.644291 -0.460131 -0.180715 -0.093033  0.146478  0.279507 -0.139348   
1374 -0.831322  0.683968 -0.171694  0.053944 -0.215934  0.151932  0.210848   
1375 -0.153540 -0.019075  0.124944 -0.236265 -0.098830  0.350150  0.107346   
1376  0.121105  0.648676  0.402525 -0.787741  0.561936  0.120264  0.164616   
1377 -0.344099 -0.749730  0.002917  0.112204 -0.211386 -0.031957 -0.177240   
1378 -0.213687 -0.442927  0.328459 -0.294232 -0.176630  0.225202 -0.221850   
1379 -0.431179  0.402677  0.771981 -0.027379 -0.533472 -0.181558 -0.112539   
1380 -0.561875 -0.173576 -0.374919 -0.035312  0.038355 -0.245425  0.129524   
1381 -0.391270  0.112758  0.303500 -0.301820 -0.298764 -0.010993 -0.258789   
1382 -0.380981  0.486749  0.620759 -0.445276 -0.439798  0.262459 -0.159901   
1383 -0.557006  0.003598  0.314881 -0.448781 -0.183089 -0.040672 -0.260305   
1384  1.009925  0.836319  0.050945 -0.675434  0.497756 -0.014065 -0.239931   
1385 -0.311472 -0.094346  0.466315 -0.199369 -0.162715 -0.170655 -0.057160   
1386  0.285251 -0.029190  0.005781 -0.704304  0.313677  0.021350 -0.381728   
1387 -0.509282  0.502521 -0.007842  0.010575 -0.258422  0.337120 -0.028097   
1388 -0.154755 -0.037092  0.809848 -0.410970 -0.246987 -0.104350 -0.316386   
1389  0.233647 -0.108442  0.290154 -0.313879 -0.044797  0.059848 -0.015814   
1390 -0.897062 -0.020093 -0.23041

Read to csv file. 

In [112]:
principalDf.to_csv("PC15.csv")

Write a function to do it for any normalised $\mathbf{Y}$ matrix. 

In [120]:
def PCA_snp(normY, chrom):
    '''
    Creates the csv file containing the 10 PCs for chromosome number "chrom" from normalised genomic matrix Y
    Params:
        normY: np.darray 
            normalised genomic matrix Y
        chrom: int
            chromosome number
    '''
    psi = np.matmul(np.transpose(normY), normY) 
    GRM = psi/len((normY))
    pca = PCA(n_components=10)
    principalComponents = pca0.fit_transform(GRM)
    principalDf = pd.DataFrame(data = principalComponents
             , columns = ['PC1', 'PC2','PC3','PC4','PC5','PC6','PC7','PC8','PC9','PC10'])
    principalDf.to_csv(f"PC{chrom}.csv")

In [117]:
PCA_snp(GRM_15, 16)